server:
  port: 8080

spring:
  application:
    name: mixIt
  profiles:
    active: local
    include: private, email
  jpa:
    open-in-view: false
  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

security:
  jwt:
    expiration-time: 86400000
    secret-key: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

mixit:
  default-image-url: https://mixit-local.s3.ap-northeast-2.amazonaws.com/_defaultimg.png
