name: Build & Deploy to EC2

on:
  push:
    branches:
      - deploy_test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew clean bootJar

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: ./build/libs/*.jar
          target: /home/${{ secrets.EC2_USERNAME }}/mixit/
          strip_components: 2

      # 5) EC2에서 기존 프로세스 종료 & 새 프로세스 실행
      - name: Restart Spring Boot on EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            APP_DIR="/home/${{ secrets.EC2_USERNAME }}/mixit"
            # mixit 폴더에 있는 첫 번째 JAR 파일 경로 탐색
            JAR_FILE=$(ls "$APP_DIR"/*.jar | head -n1)

            echo ">>> Found JAR: $JAR_FILE"
            if [ -z "$JAR_FILE" ]; then
              echo "Error: JAR 파일을 찾을 수 없습니다!"
              exit 1
            fi

            # 이미 실행 중인 프로세스가 있으면 종료
            if pgrep -f "$JAR_FILE"; then
              echo "Stopping existing application..."
              pkill -f "$JAR_FILE"
              sleep 5
            fi

            # 백그라운드로 실행
            echo "Starting application..."
            java -jar "$JAR_FILE" --spring.profiles.active=develop &